<Gerenciador>
    Menu:
        name: 'menu'
    Tarefas:
        name: 'tarefas'

<Menu>
    BoxLayout:
        orientation: 'vertical'
        padding: 200
        spacing:50
        Image:
            source:'logo.png'
            size_hint_y:None
            height:70
        Button:
            text: 'Tarefas'
            on_release: app.root.current = 'tarefas'
        Button:
            text: 'Assistente'
        Button:
            text: 'Sair'
            on_release: app.stop()



<Tarefas>:
    BoxLayout:
        orientation:'vertical'
        ActionBar:
            ActionView:
                ActionPrevious:
                    title:'voltar'
                    on_release: app.root.current = 'menu'
                ActionSeparator:
                ActionButton:
                    text: 'Sair'
                    on_release: app.stop()
        ScrollView:
            BoxLayout:
                id:box
                orientation:'vertical'
                size_hint_y: None
                height: self.minimum_height
        BoxLayout:
            size_hint_y: None
            height: 60
            TextInput:
                id:texto
            Button:
                text:'+'
                size_hint_x: None
                widht: 60
                on_release: root.addWidget()


<Tarefa>
    size_hint_y: None
    height:200
    size_font:30
    Label:
        id:label
    Button:
        text:'X'
        size_hint_x: None
        width:25
        on_release:app.root.get_screen('tarefas').ids.box.remove_widget(self.parent)

