listagem = ('Lápis', 1.75, 'Borracha', 2.00, 'Caderno', 15.90,
            'Estojo', 25.00, 'Transferidor', 4.20, 'Compasso', 9.99, 'Mochila', 120.32, 'Canetas', 22.30, 'Livro',
            34.90)
print('-' * 40)
print('{:^40}'.format('LISTAGEM DE PREÇOS'))
print('-' * 40)
print(f'{listagem[0]}', end=''), print('..........................', end=''), print(f'R$   {listagem[1]}')
print(f'{listagem[2]}', end=''), print('.......................', end=''), print(f'R$   {listagem[3]}')
print(f'{listagem[4]}', end=''), print('........................', end=''), print(f'R$   {listagem[5]}')
print(f'{listagem[6]}', end=''), print('.........................', end=''), print(f'R$   {listagem[7]}')
print(f'{listagem[8]}', end=''), print('...................', end=''), print(f'R$   {listagem[9]}')
print(f'{listagem[10]}', end=''), print('.......................', end=''), print(f'R$   {listagem[11]}')
print(f'{listagem[12]}', end=''), print('........................', end=''), print(f'R$   {listagem[13]}')
print(f'{listagem[14]}', end=''), print('........................', end=''), print(f'R$   {listagem[15]}')
print(f'{listagem[16]}', end=''), print('..........................', end=''), print(f'R$   {listagem[17]}')
print('-' * 40)
